// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('auth_test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('auth_test', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1536, height: 859 })
    await driver.findElement(By.css(".login_btn")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("Gautam@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Gautam2601&&")
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.css(".privacy-policy > input")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.css(".pi-eye")).click()
    await driver.findElement(By.css(".pi-eye-slash")).click()
    {
      const element = await driver.findElement(By.css(".pi-eye"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".pi-eye")).click()
    await driver.findElement(By.linkText("Forgot?")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).sendKeys("123")
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.linkText("Forgot?")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).sendKeys("123")
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".resubmit")).click()
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Gautam")
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Gautam2601&&")
    await driver.findElement(By.id("confirmPassword")).sendKeys("Gautam2601&&")
    await driver.findElement(By.css(".privacy-policy")).click()
    await driver.findElement(By.css(".privacy-policy")).click()
    await driver.findElement(By.css(".privacy-policy")).click()
    {
      const element = await driver.findElement(By.css(".privacy-policy"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".auth_form")).click()
    await driver.findElement(By.css(".privacy-policy > input")).click()
    await driver.findElement(By.linkText("privacy policy")).click()
    await driver.findElement(By.css(".privacy-accept-btn")).click()
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Login")).click()
  })
})
