// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('home_page_testing', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('home_page_testing', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1536, height: 859 })
    await driver.findElement(By.css(".get_started_btn > button")).click()
    await driver.findElement(By.css(".backToHome")).click()
    await driver.findElement(By.css(".get_started_btn > button")).click()
    await driver.findElement(By.css(".backToHome")).click()
    await driver.findElement(By.css(".login_btn > button")).click()
    await driver.findElement(By.css(".backToHome")).click()
    await driver.findElement(By.css(".signup_btn")).click()
    await driver.findElement(By.css(".backToHome")).click()
    await driver.findElement(By.linkText("Features")).click()
    await driver.findElement(By.linkText("How it Works?")).click()
    await driver.findElement(By.linkText("FAQs")).click()
    await driver.findElement(By.css("a > img")).click()
    await driver.findElement(By.css(".features_card:nth-child(1) p")).click()
    await driver.executeScript("window.scrollTo(0,1584)")
    await driver.findElement(By.css(".see_less > button")).click()
    await driver.findElement(By.css(".features_card:nth-child(2) p")).click()
    await driver.executeScript("window.scrollTo(0,1584)")
    await driver.findElement(By.css(".see_less > button")).click()
    await driver.findElement(By.css(".features_card:nth-child(3) p")).click()
    await driver.executeScript("window.scrollTo(0,1912.63330078125)")
    await driver.findElement(By.css(".see_less > button")).click()
    await driver.findElement(By.css(".features_card:nth-child(4) p")).click()
    await driver.findElement(By.css(".see_less > button")).click()
    await driver.findElement(By.css(".que1 img")).click()
    await driver.findElement(By.css(".que1 img")).click()
    await driver.findElement(By.css(".que2 img")).click()
    await driver.findElement(By.css(".que2 img")).click()
    await driver.findElement(By.css(".que3 img")).click()
    await driver.findElement(By.css(".que3 img")).click()
    {
      const element = await driver.findElement(By.css(".que3 img"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".que4 img")).click()
    await driver.findElement(By.css(".que4 img")).click()
    {
      const element = await driver.findElement(By.css(".que4 img"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".que5 img")).click()
    await driver.findElement(By.css(".que5 img")).click()
    await driver.findElement(By.css(".logotext > img")).click()
    await driver.findElement(By.css(".github_logo")).click()
    await driver.findElement(By.css(".footer_first_column")).click()
    await driver.findElement(By.css(".footer_first_column")).click()
    await driver.findElement(By.css(".footer_second_column")).click()
    await driver.findElement(By.css(".footer_second_column")).click()
    await driver.findElement(By.linkText("How It Works?")).click()
    await driver.findElement(By.css(".question_div")).click()
    {
      const element = await driver.findElement(By.css(".question_div"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".footer_second_column > .nav_link:nth-child(2) > a")).click()
    await driver.findElement(By.css(".footer_second_column > .nav_link:nth-child(3) > a")).click()
    await driver.findElement(By.linkText("How It Works?")).click()
    await driver.findElement(By.linkText("Privacy Policy")).click()
    await driver.findElement(By.linkText("Terms Of Service")).click()
  })
})
