// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('chatbot_testing', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('chatbot_testing', async function() {
    await driver.get("http://localhost:5173/dashboard")
    await driver.manage().window().setRect({ width: 1536, height: 859 })
    await driver.findElement(By.linkText("AI Insights")).click()
    await driver.findElement(By.css(".bot-toggle-sidebar-btn")).click()
    await driver.findElement(By.css(".bot-toggle-sidebar-btn")).click()
    await driver.findElement(By.css(".bot-toggle-sidebar-btn")).click()
    await driver.findElement(By.css(".chat-input")).click()
    await driver.findElement(By.css(".chat-input")).sendKeys("hy")
    await driver.findElement(By.css(".send-btn")).click()
    await driver.findElement(By.css(".user-bubble")).click()
    await driver.findElement(By.css(".user-bubble")).click()
    await driver.findElement(By.css(".bot-bubble")).click()
    await driver.findElement(By.css(".chat-messages")).click()
    await driver.findElement(By.css(".chat-input")).click()
    await driver.findElement(By.css(".chat-input-area")).click()
    await driver.findElement(By.css(".chat-input-area")).click()
    {
      const element = await driver.findElement(By.css(".chat-input-area"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".chat-input"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".chat-input"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".chat-input"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".chat-input")).click()
    await driver.findElement(By.css(".chat-input")).click()
    await driver.findElement(By.css(".send-btn")).click()
    await driver.findElement(By.css(".chat-input")).click()
    await driver.findElement(By.css(".chat-input")).sendKeys("give rvnl stock news")
    await driver.findElement(By.css(".chat-input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".chat-bubble:nth-child(4)")).click()
    await driver.findElement(By.css("p:nth-child(2)")).click()
    await driver.findElement(By.css(".send-btn")).click()
    await driver.findElement(By.linkText("AI Insights")).click()
    await driver.findElement(By.css(".navbar")).click()
    await driver.findElement(By.css(".profile_btn img")).click()
    {
      const element = await driver.findElement(By.css(".profile_btn img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".profileoverlay")).click()
    await driver.findElement(By.css(".bot-toggle-sidebar-btn")).click()
    await driver.findElement(By.css(".chatbot-feature-list")).click()
    await driver.findElement(By.css(".chatbot-f4 > h4")).click()
    await driver.findElement(By.css(".chatbot-f2 > p")).click()
    await driver.findElement(By.css(".chatbot-f1 > p")).click()
    await driver.findElement(By.css(".chatbot-feature > p")).click()
    await driver.findElement(By.css(".profileContainer > h3")).click()
    await driver.findElement(By.css(".profile-avatar")).click()
  })
})
