// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('auth', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('auth', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1550, height: 878 })
    await driver.findElement(By.css(".login_btn")).click()
    await driver.findElement(By.css(".email-error")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("123")
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.css(".pi-eye")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("span:nth-child(2)")).click()
    vars["win3581"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win3581"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.linkText("Forgot?")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).sendKeys("123")
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.css(".resubmit")).click()
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).click()
    {
      const element = await driver.findElement(By.id("otp"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).sendKeys("3394")
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.linkText("Forgot?")).click()
    await driver.findElement(By.linkText("Login")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Gautam")
    await driver.findElement(By.id("email")).sendKeys("modi")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).click()
    {
      const element = await driver.findElement(By.id("email"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Gautam2601&&")
    await driver.findElement(By.id("confirmPassword")).sendKeys("Gautam2601&&")
    await driver.findElement(By.css("div:nth-child(7) .pi")).click()
    await driver.findElement(By.css("div:nth-child(5) > label")).click()
    await driver.findElement(By.css(".pi-eye")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.css(".privacy-policy > input")).click()
    await driver.findElement(By.css(".submit")).click()
    await driver.findElement(By.linkText("privacy policy")).click()
    await driver.findElement(By.css(".privacy-accept-btn")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328564@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("123")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("span:nth-child(2)")).click()
    vars["win4501"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win4501"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("name")
    await driver.findElement(By.id("email")).sendKeys("mg93256@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("123")
    await driver.findElement(By.id("confirmPassword")).sendKeys("122")
    await driver.findElement(By.css("div:nth-child(5) .pi")).click()
    await driver.findElement(By.css(".pi-eye")).click()
    await driver.findElement(By.css("div:nth-child(5) .password-toggle")).click()
    await driver.findElement(By.css(".pi-eye-slash")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("g9328566@gmail.com")
    await driver.findElement(By.css("div:nth-child(5) .pi")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Gautam93@&")
    await driver.findElement(By.id("confirmPassword")).click()
    await driver.findElement(By.id("confirmPassword")).click()
    {
      const element = await driver.findElement(By.id("confirmPassword"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("confirmPassword")).click()
    await driver.findElement(By.id("confirmPassword")).sendKeys("Gautam93@&")
    await driver.findElement(By.css(".privacy-policy > input")).click()
    await driver.findElement(By.linkText("privacy policy")).click()
    await driver.findElement(By.css(".privacy-accept-btn")).click()
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).sendKeys("123")
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".resubmit")).click()
    {
      const element = await driver.findElement(By.id("otp"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("otp"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("otp"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.css(".auth_form")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.css(".email-error")).click()
    await driver.findElement(By.linkText("Forgot?")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("mg9328546@gmail.com")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("otp")).click()
    await driver.findElement(By.id("otp")).sendKeys("123")
    await driver.findElement(By.css(".submit")).click()
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".resubmit")).click()
    await driver.findElement(By.css(".backToHome")).click()
    await driver.findElement(By.css(".menu_toggle")).click()
    await driver.findElement(By.css("a:nth-child(1) > li")).click()
  })
})
