// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Dashboard Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Dashboard Test', async function() {
    // Test name: Dashboard Test
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    await driver.get("https://insight-stox-portfolio-analyzer-tra-gamma.vercel.app/dashboard")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    // 3 | click | linkText=Portfolio | 
    await driver.findElement(By.linkText("Portfolio")).click()
    // 4 | mouseOver | linkText=Dashboard | 
    {
      const element = await driver.findElement(By.linkText("Dashboard"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 6 | click | linkText=Watchlist | 
    await driver.findElement(By.linkText("Watchlist")).click()
    // 7 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 8 | mouseOver | linkText=AI Insights | 
    {
      const element = await driver.findElement(By.linkText("AI Insights"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 9 | click | linkText=AI Insights | 
    await driver.findElement(By.linkText("AI Insights")).click()
    // 10 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 11 | mouseOver | linkText=Dashboard | 
    {
      const element = await driver.findElement(By.linkText("Dashboard"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 13 | click | css=.d-stock-info:nth-child(1) .d-stock-name | 
    await driver.findElement(By.css(".d-stock-info:nth-child(1) .d-stock-name")).click()
    // 14 | mouseOver | linkText=Portfolio | 
    {
      const element = await driver.findElement(By.linkText("Portfolio"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | mouseOut | linkText=Portfolio | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 16 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 17 | mouseDown | css=.search-input | 
    {
      const element = await driver.findElement(By.css(".search-input"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 18 | mouseUp | css=.overlay | 
    {
      const element = await driver.findElement(By.css(".overlay"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 19 | click | css=.dashboard-container | 
    await driver.findElement(By.css(".dashboard-container")).click()
    // 20 | type | css=.popup-search-input | rel
    await driver.findElement(By.css(".popup-search-input")).sendKeys("rel")
    // 21 | click | css=.result-item:nth-child(1) | 
    await driver.findElement(By.css(".result-item:nth-child(1)")).click()
    // 22 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 23 | click | css=.trending-stock-item:nth-child(1) .stock-nse | 
    await driver.findElement(By.css(".trending-stock-item:nth-child(1) .stock-nse")).click()
    // 24 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 25 | runScript | window.scrollTo(0,164.8000030517578) | 
    await driver.executeScript("window.scrollTo(0,164.8000030517578)")
    // 26 | click | css=.portfoliochart-btn:nth-child(2) | 
    await driver.findElement(By.css(".portfoliochart-btn:nth-child(2)")).click()
    // 27 | click | css=.portfoliochart-btn:nth-child(3) | 
    await driver.findElement(By.css(".portfoliochart-btn:nth-child(3)")).click()
    // 28 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 29 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 30 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 31 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 32 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 33 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 34 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 35 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 36 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 37 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 38 | click | css=.chart-wrapper > canvas | 
    await driver.findElement(By.css(".chart-wrapper > canvas")).click()
    // 39 | click | css=.gainer-row:nth-child(2) | 
    await driver.findElement(By.css(".gainer-row:nth-child(2)")).click()
    // 40 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 41 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
    // 42 | runScript | window.scrollTo(0,492) | 
    await driver.executeScript("window.scrollTo(0,492)")
    // 43 | runScript | window.scrollTo(0,1600) | 
    await driver.executeScript("window.scrollTo(0,1600)")
    // 44 | click | css=.news-item:nth-child(6) > .news-headline | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 45 | storeWindowHandle | root | 
    await driver.findElement(By.css(".news-item:nth-child(6) > .news-headline")).click()
    // 46 | selectWindow | handle=${win1329} | 
    vars["win1329"] = await waitForWindow(2000)
    // 47 | selectWindow | handle=${root} | 
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win1329"])
    await driver.switchTo().window(vars["root"])
  })
})
