// Generated by Selenium IDE
const { Builder, By, Key } = require('selenium-webdriver')
const assert = require('assert')

describe('HelpSupport_Page_Testing', function() {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })

  afterEach(async function() {
    await driver.quit()
  })

  it('Help & Support GUI Test', async function() {
    await driver.get('http://localhost:5173/my-profile')

    await driver.findElement(By.css('.Sidebar-item:nth-child(5)')).click()

    await driver.findElement(By.css('.quick-help-btn:nth-child(1)')).click()
    await driver.findElement(By.css('.btn-primary:nth-child(4)')).click()

    await driver.findElement(By.css('.quick-help-btn:nth-child(2)')).click()
    await driver.findElement(By.css('.detailed-content-card > .btn-primary')).click()

    await driver.findElement(By.css('.quick-help-btn:nth-child(3)')).click()
    await driver.findElement(By.css('.detailed-content-card > .btn-primary')).click()

    await driver.findElement(By.css('.quick-help-btn:nth-child(4)')).click()
    await driver.findElement(By.css('.modal-overlay')).click()

    const msg = await driver.findElement(By.id('message-input'))
    await msg.sendKeys('what are you doing?')

    await driver.findElement(By.css('.submit-ticket-btn')).click()
    await driver.switchTo().alert().accept()

    const feedback = await driver.findElement(By.id('feedback-input'))
    await feedback.sendKeys('i am fine.')

    await driver.findElement(
      By.css('.help-section:nth-child(4) .btn-primary')
    ).click()

    await driver.switchTo().alert().accept()
  })
})
