// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('My Profile Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('My Profile Page', async function() {
    await driver.get("http://localhost:5173/dashboard")
    {
      const element = await driver.findElement(By.linkText("Compare Stocks"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("button > img")).click()
    await driver.findElement(By.css("li:nth-child(1)")).click()
    await driver.findElement(By.css(".Sidebar-item:nth-child(2)")).click()
    await driver.findElement(By.css(".Sidebar-item:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".Sidebar-item:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".Sidebar-item:nth-child(4)")).click()
    await driver.findElement(By.css(".Sidebar-item:nth-child(5)")).click()
    await driver.findElement(By.css(".Sidebar-item:nth-child(1)")).click()
    await driver.findElement(By.css(".myPage_ChangePhoto")).click()
    {
      const element = await driver.findElement(By.css(".myPage_InvExpList"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_InvExpList"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_InvExpList"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".myPage_InvExpList")).click()
    {
      const dropdown = await driver.findElement(By.css(".myPage_InvExpList"))
      await dropdown.findElement(By.xpath("//option[. = 'Expert']")).click()
    }
    await driver.findElement(By.css(".myPage_InvExpList > option:nth-child(4)")).click()
    {
      const element = await driver.findElement(By.css(".myPage_RiskProfList"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_RiskProfList"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_RiskProfList"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".myPage_RiskProfList")).click()
    {
      const dropdown = await driver.findElement(By.css(".myPage_RiskProfList"))
      await dropdown.findElement(By.xpath("//option[. = 'Medium - Moderate']")).click()
    }
    await driver.findElement(By.css(".myPage_RiskProfList > option:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".myPage_FinGoalList"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_FinGoalList"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_FinGoalList"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".myPage_FinGoalList")).click()
    {
      const dropdown = await driver.findElement(By.css(".myPage_FinGoalList"))
      await dropdown.findElement(By.xpath("//option[. = 'Income generation']")).click()
    }
    await driver.findElement(By.css(".myPage_FinGoalList > option:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".myPage_InvHorizonList"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_InvHorizonList"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".myPage_InvHorizonList"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".myPage_InvHorizonList")).click()
    {
      const dropdown = await driver.findElement(By.css(".myPage_InvHorizonList"))
      await dropdown.findElement(By.xpath("//option[. = 'Medium-term (3-10 years)']")).click()
    }
    await driver.findElement(By.css(".myPage_InvHorizonList > option:nth-child(3)")).click()
    await driver.findElement(By.css(".myPage_InfRow5 .myPage_EditDetails")).click()
    await driver.findElement(By.css(".myPage_CancelBtn")).click()
    await driver.findElement(By.css(".myPage_InfRow5 .myPage_EditDetails")).click()
    await driver.findElement(By.css(".myPage_password-toggle1 .pi")).click()
    await driver.findElement(By.css(".myPage_password-toggle2 .pi")).click()
    await driver.findElement(By.css(".myPage_password-toggle2 .pi")).click()
    await driver.findElement(By.css(".pi-eye-slash")).click()
    await driver.findElement(By.css(".myPage_CurrPass > input")).click()
    await driver.findElement(By.css(".myPage_CurrPass > input")).sendKeys("AaVvBb126@&")
    await driver.findElement(By.css(".myPage_NewPass > input")).sendKeys("AaVvBb126@@")
    await driver.findElement(By.css(".myPage_ConfPass > input")).sendKeys("AaVvBb126@@")
    await driver.findElement(By.css(".myPage_password-toggle3 .pi")).click()
    await driver.findElement(By.css(".pi-eye-slash")).click()
    await driver.findElement(By.css(".myPage_SaveBtn")).click()
    await driver.findElement(By.css(".myPage_CancelBtn")).click()
    await driver.findElement(By.css(".myPage_InfRow1 .myPage_EditDetails")).click()
    await driver.findElement(By.css("input:nth-child(1)")).click()
    await driver.findElement(By.css("input:nth-child(1)")).sendKeys("Ayush D")
    await driver.findElement(By.css(".myPage_SaveBtn")).click()
  })
})
