// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Portfolio Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Portfolio Page', async function() {
    await driver.get("https://insight-stox-portfolio-analyzer-tra-gamma.vercel.app/portfolio")
    await driver.findElement(By.css(".portfoliochart-btn:nth-child(2)")).click()
    await driver.findElement(By.css(".portfoliochart-btn:nth-child(3)")).click()
    await driver.findElement(By.css(".portfolio-add-stk-btn")).click()
    {
      const element = await driver.findElement(By.css(".portfolio-add-stk-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".portfolio-btn:nth-child(3)")).click()
    await driver.findElement(By.css(".portfolio-btn:nth-child(2)")).click()
    await driver.findElement(By.css(".portfolio-btn:nth-child(1)")).click()
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.linkText("Portfolio"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Portfolio")).click()
    await driver.findElement(By.css(".profile_btn > button")).click()
    {
      const element = await driver.findElement(By.css("button > img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".profileoverlay")).click()
  })
})
