// Generated by Selenium IDE
const { Builder, By } = require('selenium-webdriver')
const assert = require('assert')

describe('Preference_Page_Testing', function() {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })

  afterEach(async function() {
    await driver.quit()
  })

  it('Preference Page GUI Test', async function() {
    await driver.get('http://localhost:5173/my-profile')

    await driver.findElement(By.css('.Sidebar-item:nth-child(4)')).click()

    await driver.findElement(By.id('theme-select')).click()
    await driver.findElement(By.xpath("//option[.='Dark']")).click()
    await driver.switchTo().alert().accept()

    await driver.findElement(By.id('theme-select')).click()
    await driver.findElement(By.xpath("//option[.='Light']")).click()
    await driver.switchTo().alert().accept()

    await driver.findElement(By.id('layout-select')).click()
    await driver.findElement(
      By.xpath("//option[.='Detailed (Advanced Insights)']")
    ).click()
    await driver.switchTo().alert().accept()

    await driver.findElement(By.id('layout-select')).click()
    await driver.findElement(
      By.xpath("//option[.='Simple (Essential Metrics)']")
    ).click()
    await driver.switchTo().alert().accept()
  })
})
