// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Stock Details page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Stock Details page', async function() {
    await driver.get("http://localhost:5173/dashboard")
    await driver.findElement(By.css(".trending-stock-item:nth-child(6) .stock-nse")).click()
    await driver.findElement(By.linkText("Performance")).click()
    await driver.findElement(By.linkText("Fundamentals")).click()
    await driver.findElement(By.linkText("Financials")).click()
    await driver.findElement(By.linkText("News")).click()
    await driver.findElement(By.linkText("About Company")).click()
    await driver.findElement(By.css(".range-btn:nth-child(1)")).click()
    await driver.findElement(By.css(".range-btn:nth-child(2)")).click()
    await driver.findElement(By.css(".range-btn:nth-child(3)")).click()
    await driver.findElement(By.css(".range-btn:nth-child(4)")).click()
    await driver.findElement(By.css(".stk-add-watchlist")).click()
    await driver.findElement(By.css(".stk-add")).click()
    await driver.findElement(By.css("input:nth-child(1)")).click()
    await driver.findElement(By.css(".controls > button:nth-child(1)")).click()
    await driver.findElement(By.css(".controls > button:nth-child(2)")).click()
    await driver.findElement(By.css("input:nth-child(1)")).click()
    await driver.findElement(By.css("input:nth-child(1)")).sendKeys("12")
    await driver.findElement(By.css(".model-confirm-btn")).click()
    await driver.findElement(By.css(".stk-rmv")).click()
    {
      const element = await driver.findElement(By.css(".stk-rmv"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".model-toggle-container")).click()
    await driver.findElement(By.css(".model-buy")).click()
    await driver.findElement(By.css(".model-sell")).click()
    await driver.findElement(By.css("input:nth-child(1)")).click()
    await driver.findElement(By.css("input:nth-child(1)")).sendKeys("12")
    await driver.findElement(By.css(".model-confirm-btn")).click()
    await driver.findElement(By.css("button > img")).click()
    await driver.findElement(By.css(".profileoverlay")).click()
  })
})
