// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('watchlist', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('watchlist', async function() {
    await driver.get("http://localhost:5173/watchlist")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".watchlist")).click()
    await driver.findElement(By.css(".search-input")).click()
    await driver.findElement(By.css(".popup-search-input")).sendKeys("reliance")
    await driver.findElement(By.css(".result-item:nth-child(2) .pi")).click()
    await driver.findElement(By.css(".search-container > input")).click()
    await driver.findElement(By.css(".search-container > input")).sendKeys("reliance")
    await driver.findElement(By.css(".action-btn > span")).click()
    await driver.findElement(By.css(".search-container > input")).click()
    await driver.findElement(By.css(".search-container > input")).click()
    {
      const element = await driver.findElement(By.css(".search-container > input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".search-container > input")).clear()
    await driver.findElement(By.css(".filter-btn")).click()
    await driver.findElement(By.id("gainers")).click()
    await driver.findElement(By.css(".apply-filter-btn")).click()
    await driver.findElement(By.css(".filter-btn > img")).click()
    await driver.findElement(By.css(".clear-filter-btn")).click()
    await driver.findElement(By.css(".filter-modal-overlay")).click()
    await driver.findElement(By.css(".filter-btn > img")).click()
    await driver.findElement(By.id("large-cap")).click()
    await driver.findElement(By.css(".apply-filter-btn")).click()
    await driver.findElement(By.css(".filter-btn")).click()
    await driver.findElement(By.css(".clear-filter-btn")).click()
    await driver.findElement(By.css(".apply-filter-btn")).click()
    await driver.findElement(By.css(".watchlist")).click()
    await driver.findElement(By.css(".table-stock:nth-child(1) > td:nth-child(2)")).click()
    await driver.findElement(By.linkText("Watchlist")).click()
    await driver.findElement(By.css(".search-input")).click()
    await driver.findElement(By.css(".popup-search-input")).sendKeys("titan")
    await driver.findElement(By.css(".result-item:nth-child(1)")).click()
  })
})
